### ISSUE TITLE
repository: add description and topics

### ISSUE THREAD

**Issue by dweomer** [edgexfoundry/git-semver#2]
See my fork of this repository for an example: https://github.com/dweomer/git-semver

DESCRIPTION: "Opinionated GIT repository Semantic Versioning"

TOPICS:

- git
- git-cli
- semver
- semantic-versioning
- golang

**Comment by jamesrgregg** [comment]
@dweomer is this still an open issue or can it be closed?

**Comment by dweomer** [comment]
@jamesrgregg i don't know that i would go so far as to call it a "problem" but it is an extant gap, IMO:
![Screen Shot 2019-06-28 at 12 57 23 PM](https://user-images.githubusercontent.com/1033444/60367947-7483ed00-99a4-11e9-8c91-bbc6d840360e.png)

**Comment by jamesrgregg** [comment]
Is it something that should be prioritized and worked or not?  As I start to convert to the new boards we should include work we plan to complete or icebox it.

Sent from my iPhone

On Jun 28, 2019, at 12:59 PM, Jacob Blain Christen <notifications@github.com<mailto:notifications@github.com>> wrote:


@jamesrgregg<https://github.com/jamesrgregg> i don't know that i would go so far as to call it a "problem" but it is an extant gap, IMO:
[Screen Shot 2019-06-28 at 12 57 23 PM]<https://user-images.githubusercontent.com/1033444/60367947-7483ed00-99a4-11e9-8c91-bbc6d840360e.png>

**Comment by jamesrgregg** [comment]
Will not work as it requires TSC approval to add metadata to a repo that adds no value .
