### ISSUE TITLE
The git semver build is broken since we turned on the new github org. 

### ISSUE THREAD

**Issue by lranjbar** [edgexfoundry/git-semver#31]
Test the existing Jenkinsfile with the github branch source plugin. Also, may need to refactor based of new implementation detail decisions.

Note: Need labels geneva, phase 2

**Comment by jamesrgregg** [comment]
[US5372](https://rally1.rallydev.com/#/detail/userstory/334620926908?fdp=true): EdgeX DevOps: Update git-semver Jenkinsfile to work with the new github org

**Comment by jamesrgregg** [comment]
Need to make changes to make the build compatible with edgeXBuildGoApp function.
Current build is broken with error: _Project Settings File id (settingsFile) is required for the docker login script._
