### ISSUE TITLE
Git semver is unable to determine branch for HEAD in Jenkins job

### ISSUE THREAD

**Issue by soda480** [edgexfoundry/git-semver#47]
This only happens when running inside Jenkins: 

Open(): unable to determine branch for HEAD

The affect this has is that when someone re-executes a job on a release stream it will tag, bump and push semver version for the associated repo even though HEAD is already tagged.

This wasn't the behavior before when running in JJB, it seemed to have started after we  implemented Github org plugin

**Comment by jamesrgregg** [comment]
[DE801](https://rally1.rallydev.com/#/detail/defect/379528989984?fdp=true): Git semver is unable to determine branch for HEAD in Jenkins job

**Comment by jamesrgregg** [comment]
Now converted to [US7280](https://rally1.rallydev.com/#/detail/userstory/436899589488?fdp=true): EdgeX DevOps: Git semver is unable to determine branch for HEAD in Jenkins job
